package com.mobilepos.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MetricAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetricAllPropertiesEquals(Metric expected, Metric actual) {
        assertMetricAutoGeneratedPropertiesEquals(expected, actual);
        assertMetricAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetricAllUpdatablePropertiesEquals(Metric expected, Metric actual) {
        assertMetricUpdatableFieldsEquals(expected, actual);
        assertMetricUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetricAutoGeneratedPropertiesEquals(Metric expected, Metric actual) {
        assertThat(expected)
            .as("Verify Metric auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetricUpdatableFieldsEquals(Metric expected, Metric actual) {
        assertThat(expected)
            .as("Verify Metric relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()))
            .satisfies(e -> assertThat(e.getNotes()).as("check notes").isEqualTo(actual.getNotes()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMetricUpdatableRelationshipsEquals(Metric expected, Metric actual) {}
}
