package com.mobilepos.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class RegencyAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegencyAllPropertiesEquals(Regency expected, Regency actual) {
        assertRegencyAutoGeneratedPropertiesEquals(expected, actual);
        assertRegencyAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegencyAllUpdatablePropertiesEquals(Regency expected, Regency actual) {
        assertRegencyUpdatableFieldsEquals(expected, actual);
        assertRegencyUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegencyAutoGeneratedPropertiesEquals(Regency expected, Regency actual) {
        assertThat(expected)
            .as("Verify Regency auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegencyUpdatableFieldsEquals(Regency expected, Regency actual) {
        assertThat(expected)
            .as("Verify Regency relevant properties")
            .satisfies(e -> assertThat(e.getName()).as("check name").isEqualTo(actual.getName()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertRegencyUpdatableRelationshipsEquals(Regency expected, Regency actual) {
        assertThat(expected)
            .as("Verify Regency relationships")
            .satisfies(e -> assertThat(e.getProvince()).as("check province").isEqualTo(actual.getProvince()));
    }
}
